export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FALIURE = 'PROFILE_FALIURE'


export const VAULT_REQUEST = 'VAULT_REQUEST'
export const VAULT_SUCCESS = 'VAULT_SUCCESS'
export const VAULT_FALIURE = 'VAULT_FALIURE'