// FOR POST EXPENSE 
export const POST_EXPENSE_REQUEST = "POST_EXPENSE_REQUEST"
export const POST_EXPENSE_SUCCESS = "POST_EXPENSE_SUCCESS"
export const POST_EXPENSE_FAILURE = "POST_EXPENSE_FAILURE"

// FOR GET EXPENSE 
export const EXPENSE_REQUEST = "EXPENSE_REQUEST"
export const EXPENSE_SUCCESS = "EXPENSE_SUCCESS"
export const EXPENSE_FAILURE = "EXPENSE_FAILURE"